package daniil.backend.enums

enum class ErrorCode {
    USER_NOT_FOUND,
    VIDEO_NOT_FOUND,
    CHANNEL_NOT_FOUND,
    USER_ALREADY_EXISTS,
    WRONG_PASSWORD,
    TOKEN_NOT_FOUND,
    EXPIRED_TOKEN,
    USER_HAS_NO_PERMISSION,
    BAD_PASSWORD,
    VALIDATION_ERROR,
    SERVICE_ERROR,
    TOKEN_ALREADY_EXISTS,
    USER_NOT_REGISTERED,
    BLOCKED_USER,
    VIDEO_IS_HIDDEN,
    VIDEO_IS_BLOCKED,
    LIKE_NOT_FOUND,
    USER_ALREADY_SUBSCRIBED
}
