spring:
  #flyway:
  #  baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
  sql:
    init:
      mode: always
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

client:
  url: http://localhost:3000

jwt:
  uri: /auth/**
  header: Authorization
  prefix: Bearer
  expiration: 3000
  secret: JwtSuperBigFuckGigaBigBigBigBigBigSecretYeah
  ignorePath:
    - /auth/login
    - /auth/register
    - /auth/reset-password
    - /auth/forgot-password
    - /auth/confirm-registration
    - /swagger-ui
    - /v3/api-docs
    - /favicon.ico
    - /swagger-resources
    - /actuator
    - /api/ws

mail:
  isActive: true
  host: smtp.gmail.com
  port: 587
  username: ${MAIL}
  password: ${PASSWORD}
  from: ${MAIL}
  protocol: smtp
  auth: true
  tls: true
  debug: true


#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type: TRACE
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework: TRACE